Update to Zabbix port configurations
firewalld/firewalld pull request #1072
Opened 2023-01-05 09:28 UTC by jxlambda

### Hello, project firewalld!

We at Zabbix had a feature request filed ([ZBXNEXT-4737](https://support.zabbix.com/browse/ZBXNEXT-4737)) that requested we add `firewalld` configurations for networking Zabbix components.

In the course of discussion, we became aware that `firewalld` included configurations for Zabbix components [5 years ago](https://github.com/firewalld/firewalld/commit/bbf127bde23da98eae2697a3db6abdaa5a96fbb7), and after reviewing them, decided to contribute an update to them, hence this PR.

The gist of changes can be summarised as follows:
* a configuration for the Zabbix Java Gateway component was added ([zabbix-java-gateway.xml](https://github.com/firewalld/firewalld/compare/master...jxlambda:firewalld:master#diff-92c8d4f018bdd935586d4dbd54e27f134a1f42965cdd8cf90a0f3e9b6e175e4f))
* the `zabbix-server.xml` was renamed to `zabbix-trapper.xml`
  * the rationale for this is that the ports described are used by both the server and the proxy components
  * this is also the name used by IANA in their port assignment listings
* the descriptions have been updated to reflect the ports use, rather than describing the component that uses it

I've also listed the 10050/udp and 10051/udp ports in the configurations, as IANA has allocated them along-side their tcp equivalents, although in practice, these components don't use UDP, so maybe that's something to consider outright.

Feedback greatly appreciated!

2023-01-25 10:36 UTC, jxlambda commented
Hello, again!

I just wanted to remind about this pull request and ask for some feedback on what could or should be changed.

Thank you!

2023-01-25 16:44 UTC, erig0 requested changes
> the zabbix-server.xml was renamed to zabbix-trapper.xml

Removing a service definition is a breaking change. I suggest adding `zabbix-trapper.xml` as you have, but make `zabbix-server` an alias to the new `zabbix-trapper` definition.

To do that, zabbix-server can `include` zabbix-trapper.

```xml
<include service="zabbix-trapper" />
```

---

Lastly, please update `config/Makefile.am` and `po/POTFILES.in` with the new services.

Otherwise, lgtm.

2023-01-25 16:45 UTC, erig0 commented
> I just wanted to remind about this pull request and ask for some feedback on what could or should be changed.

Thanks for the gentle ping and patience. I was on medical leave.

2023-01-25 16:50 UTC, erig0 commented
> their TCP equivalents, although in practice, these components don't use UDP, so maybe that's something to consider outright.

It's up to the Zabbix project whether including the UDP ports makes sense. You (zabbix) know what's best for your users. :)

2023-01-26 13:37 UTC, jxlambda commented
After a brief discussion, we decided to remove the UDP port declarations from the configurations, which was done in [78e46a6](https://github.com/firewalld/firewalld/pull/1072/commits/78e46a600053e790723730303c1ba224dff65776).

I added the configurations to the Makefile template and the translatable file listing for the new files in [26f7262](https://github.com/firewalld/firewalld/pull/1072/commits/26f7262a4da77c2b8d3fecc131c61c023e53401a), but am wondering if the `zabbix-server.xml` should be excluded, now that it includes the contents of `zabbix-trapper.xml`, which is processed in its own right.

2023-01-26 13:39 UTC, erig0 commented
> am wondering if the zabbix-server.xml should be excluded

Nope. It should still be in the makefile and potfiles list.

2023-01-26 13:58 UTC, erig0 commented
Hi, I squashed the commits together and changed the description of `zabbix-server`. I'm happy with it.

If you are also happy, please ACK it and I'll merge.

2023-01-26 14:02 UTC, erig0 approved these changes

2023-01-26 14:17 UTC, jxlambda commented
I'm happy with the final result.

2023-01-26 14:22 UTC, erig0 commented
> I'm happy with the final result.

Great. Merging. Thanks again for the PR!

2023-01-26 14:22 UTC, merged