feat(service) Add syscomlan
firewalld/firewalld pull request #1118
Opened 2023-05-05 18:46 UTC by jcpunk

Port 1065 is registered to syscomlan at IANA.  I'll confess I don't totally understand what it is for, but one of our local applications is using this port so I figured I'd share.

2023-05-08 18:47 UTC, erig0 requested changes

2023-05-08 18:47 UTC, erig0 commented on config/services/syscomlan.xml
> +<service>
Should be `</service>`.

2023-05-08 23:35 UTC, jcpunk commented on config/services/syscomlan.xml
> +<service>
In theory that is fixed now.

2023-05-11 19:44 UTC, erig0 approved these changes

2023-05-11 19:44 UTC, merged