[th/xml-schema] restore XSD XML schemas for validating config files
firewalld/firewalld pull request #1198
Opened 2023-08-17 09:53 UTC by thom311

While firewalld command line tools now have an option `--check-config`,
it's still useful to have a scheme for our XML files.
    
Revert the removal of the XSD schemas.
    
This replaces/obsoletes pull request [1], because I think we should
restore the previous schema, instead of writing a new one.
    
This reverts the removal from commit 81d3d6a7d84bc34a18ddd4ab6153f0dafb2fa17e.

[1] https://github.com/firewalld/firewalld/pull/492

Fixes: https://github.com/firewalld/firewalld/issues/488

2023-08-24 19:13 UTC, erig0 requested changes
Please split the commit `fix(config): adjust XML schemas to allow previously unsupported parts` so it does not modify the XML and the schema in the same commit. AFIAICS, there is no reason to do them in the same commit.

Otherwise, lgtm.

2023-08-24 19:13 UTC, erig0 commented on config/services/cratedb.xml
> +  <include service="postgresql"/>
Is this change meant to be part of this commit?

2023-08-24 19:13 UTC, erig0 commented on config/services/minidlna.xml
> +  <port protocol="tcp" port="8200"/>
ditto

2023-08-24 19:13 UTC, erig0 commented on config/services/plex.xml
> +  <include service="ssdp"/> <!-- Plex DLNA -->
ditto

2023-08-24 19:13 UTC, erig0 commented on config/Makefile.am
I assume the intention here is to get extra test coverage for xmlschema by adding these. I don't think we should worry about synchronizing these with their upstream (libvirt, et al.) counterparts. In that regard, then I think it's fine to add these.

2023-08-24 20:46 UTC, thom311 commented on config/Makefile.am
exactly. I extended the commit message about that.

2023-08-24 20:48 UTC, thom311 commented
> Please split the commit `fix(config): adjust XML schemas to allow previously unsupported parts` so it does not modify the XML and the schema in the same commit. AFIAICS, there is no reason to do them in the same commit.

split.

Branch repushed.

2023-08-25 19:20 UTC, erig0 approved these changes

2023-08-25 19:20 UTC, merged