[th/deprecate-lockdown-pt1] deprecate Lockdown API (part 1)
firewalld/firewalld pull request #1269
Opened 2024-01-10 15:15 UTC by thom311

No change in behavior, just documentation update and D-Bus annotation (`org.freedesktop.DBus.Deprecated`).

https://github.com/firewalld/firewalld/issues/1266

A future part will remove part of Lockdown code.

Also try to improve how D-Bus methods are deprecated. The ability to annotate methods/signals (with `org.freedesktop.DBus.Deprecated`) really should have been improved in dbus-python project from the start. Maybe I should still send a patch for that. Regardless, even if dbus-python gets the feature today, we couldn't rely on it from firewalld yet.

2024-01-11 09:34 UTC, thom311 commented
[Here](https://gitlab.freedesktop.org/dbus/dbus-python/-/merge_requests/30) dbus-python would gain support for an `is_deprecated` argument. If we ever could rely on this, we could drop code from firewalld.

2024-01-11 16:07 UTC, erig0 requested changes
This looks great. Add the missing change to `firewall-offline-cmd` and I'll merge.

2024-01-11 16:07 UTC, erig0 commented on doc/xml/firewalld.dbus.xml
Please add the CLI help text deprecation notice to `firewall-offline-cmd` as well.

2024-01-11 23:45 UTC, thom311 commented on doc/xml/firewalld.dbus.xml
done (yes?)

2024-01-12 14:12 UTC, erig0 approved these changes

2024-01-12 14:13 UTC, merged