[th/with-transaction] cleanup `use_transaction` handling
firewalld/firewalld pull request #1305
Opened 2024-02-12 13:39 UTC by thom311

I think most functions that have a `use_transaction` argument, should not optimally take a transaction. Instead, their callers should always provide one.

But that is not immediately obvious to fix, without potential changes in behavior (which may be correct). For example, there are calls like `transaction.add_pre(self._fw.flush_direct_backends)`, where the flush is not done with a transaction. Maybe it should be.

Anyway. Add and use a context manager for the "use_transaction" pattern, to simplify the code.

2024-02-13 15:53 UTC, erig0 requested changes
Otherwise this looks good. Sucks that we have to increase the indent level for so much code though.

2024-02-13 16:04 UTC, thom311 commented on src/firewall/core/fw.py
> +                        ctxself.transaction.add_pre(self.full_check_config)
That's true. But that is what the code on `main` already does.

Do you suggest to just drop this `add_pre()` altogether (in a first commit)?

2024-02-13 16:05 UTC, thom311 commented
> Sucks that we have to increase the indent level for so much code though.

yes. I find that is often a style problem with `with` statements. But I don't see a good alternative.

2024-02-13 17:06 UTC, erig0 commented on src/firewall/core/fw.py
> +                        ctxself.transaction.add_pre(self.full_check_config)
No. I'm saying don't add it in the contextmanager.

2024-02-13 17:09 UTC, thom311 commented on src/firewall/core/fw.py
> +                        ctxself.transaction.add_pre(self.full_check_config)
where then?

2024-02-13 17:09 UTC, thom311 commented on src/firewall/core/fw.py
> +                        ctxself.transaction.add_pre(self.full_check_config)
> where then?

never mind.

2024-02-13 17:10 UTC, thom311 commented on src/firewall/core/fw.py
> +                        ctxself.transaction.add_pre(self.full_check_config)
I had before
```python
    def with_transaction(self, *args, **kwargs):
        wt = self._fw.with_transaction(*args, **kwargs)
        if wt.is_temporary:
            wt.transaction.add_pre(self._fw.full_check_config)
        return wt
```
which has the same behavior (as `main` and as the current branch).

what you suggest, is a different behavior. And it seems wrong, that if we are called with an existing transaction, that we then also add this pre-check .

2024-02-13 20:36 UTC, erig0 commented on src/firewall/core/fw.py
> +                        ctxself.transaction.add_pre(self.full_check_config)
The original code was never called with an existing transaction. The original function was called `new_transaction()`.

2024-02-13 20:59 UTC, thom311 commented on src/firewall/core/fw.py
> +                        ctxself.transaction.add_pre(self.full_check_config)
I don't understand.

> The original code was never called with an existing transaction. The original function was called new_transaction().

Yes. `FirewallPolicy.new_transaction()` and `FirewallZone.new_transaction()` did `add_pre()` for new/temporary transaction only. The behavior was exactly the same, as on the current `th/with-transaction` branch (see `with_full_check_config=True` parameter).

That is unlike your suggestion from https://github.com/firewalld/firewalld/pull/1305#discussion_r1488101236, which does it always.

That is like my suggestion from https://github.com/firewalld/firewalld/pull/1305#discussion_r1488274105 . But that is just another way to do the same as what  `th/with-transaction` branch does (and not necessarily better).

---

Anyway. What's your suggestion?

2024-02-13 21:28 UTC, erig0 commented on src/firewall/core/fw.py
> +                        ctxself.transaction.add_pre(self.full_check_config)
> Yes. FirewallPolicy.new_transaction() and FirewallZone.new_transaction() did add_pre() for new/temporary transaction only. The behavior was exactly the same, as on the current th/with-transaction branch (see with_full_check_config=True parameter).

Correct that the behavior is the same. I'm saying you should not be calling `add_pre()`  in the transaction context manager. I think adding pre-transaction hooks should be explicit for the config checks. I prefer what you have a couple comments up.

> That is unlike your suggestion from https://github.com/firewalld/firewalld/pull/1305#discussion_r1488101236, which does it always.

Right. I was looking only at `new_transaction()`. But you're passing `use_transaction` all the way down to the contextmanager. I don't like it, but I see the why now.

Can we at least remove all the duplicate `with_transaction()` definitions? Let's get to having a single one. There are duplicates in: `fw_direct.py`, `fw_policy.py`, and `fw_zone.py`.

2024-02-14 08:21 UTC, thom311 commented on src/firewall/core/fw.py
> +                        ctxself.transaction.add_pre(self.full_check_config)
pushed a fixup.

2024-02-14 23:02 UTC, erig0 commented
@thom311, please review the commits I added on top.

2024-02-19 10:46 UTC, thom311 commented
> @thom311, please review the commits I added on top.

Pushed one fixup commit. Branch lgtm.

2024-02-27 17:09 UTC, erig0 approved these changes

2024-02-27 17:09 UTC, merged