[th/applet-translation-fix] fix sl.po translation and `firewall.functions.wrong_args_for_callable()`
firewalld/firewalld pull request #1311
Opened 2024-02-21 09:12 UTC by thom311

Fixes https://github.com/firewalld/firewalld/issues/1310

2024-02-27 17:15 UTC, erig0 requested changes

2024-02-27 17:15 UTC, erig0 commented on po/sl.po
Hrm. I think the real fix here is no not use python format strings inside `_()`. Can we fix the code instead?

2024-02-27 19:21 UTC, thom311 commented on po/sl.po
why would it be wrong to have format strings inside translated strings? That seems a very common thing to do.
E.g. `printf(_("profile \"%s\" is bad"), name)`.

What `gettext()` should really get right, is to implement the printf format strings, and reject lookup a string where the format strings don't match. Granted, normally `gettext.gettext()` is for plain strings, so there should be a `gettext.getformattext()` where this special casing of format strings is implemented. Aside that not happening, there is nothing for firewalld to do.

2024-04-11 19:05 UTC, erig0 requested changes

2024-04-11 19:05 UTC, erig0 commented on po/sl.po
These are not the same thing. Your example `_("profile \"%s\" is bad")` has `%s` as the "format" string. But f-strings have a variable name which is often an english word, e.g. `entry`.

As I said, this could be fixed on the code side and makes sure we don't have the same translation mistakes.

```diff
diff --git a/src/firewall-applet.in b/src/firewall-applet.in
index 0d4a3067e0ab..1e0491d2c4a2 100755
--- a/src/firewall-applet.in
+++ b/src/firewall-applet.in
@@ -720,7 +720,7 @@ class TrayApplet(QtWidgets.QSystemTrayIcon):
             zone = nm_get_zone_of_connection(connection)
             connections[connection] = [zone, connection_name]
 
-        binding = _("{entry} (Zone: {zone})")
+        binding = _("{} (Zone: {})").format(entry, zone)
 
         # add NM controlled bindings
         for connection in sorted(connections):
```

2024-04-12 07:46 UTC, thom311 commented on po/sl.po
> binding = "{entry} (" + _("Zone") + ": {zone})"

I don't think that is right. This would restrict how languages may translate things. E.g. you have right-to-left languages or some languages may use different symbols than `:` and `(`/`)`.

Even if this particular phrase would in all languages follow this structure, such an approach does not work in general. Translations also usually don't do this. Do you have a resource where such an approach is suggested?

In any case, this branch fixes two actual bugs:
- a bug in `wrong_args_for_callable()`
- a bug in translation, which applies to the currently existing texts (and is known to break the application).

Reworking the code by restructuring the translated text is a separate topic (and IMO should not be done).

2024-04-12 08:02 UTC, thom311 commented on po/sl.po
>  But f-strings have a variable name which is often an english word, e.g. entry.

btw, Python f-strings are IMO `f"some string with an {argument}`, which are understood by the language.

Here, we have a string that is passed to `str.format()`.

For example
```python
     binding = _("{entry} (Zone: {zone})")
     ... binding.format(zone=zone, entry=connection_name) ...
```

These variable names are only a feature of `str.format()`. `str.format()` also supports positional arguments. This could be similarly written as
```python
     binding = _("{} (Zone: {})")
     ... binding.format(connection_name, zone) ...
```
and translators could translate that to `"{} (Zone: {})" or they can swap the order like `"(Zone {0}) - {1}"`.

In any case, it's common that translated strings contain parameters, which then are replaced by some `printf()` or `str.format()` mechanism. It important, that translations don't mess this up. Otherwise, we get errors. For example: `python -c 's = "a:{}, b:{}"; t = s.format(1,2); print(t); s.format(1)'` also raises an exception.

2024-04-12 08:17 UTC, thom311 commented on po/sl.po
according to https://github.com/OCA/pylint-odoo/issues/302#issue-758472967 , it seems suggested to use `%` operator, which is s safer to not allow translations execute unwanted code.

It however still can raise exceptions, 
```
$ python -c 'print("%s -- %s" % (1,))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: not enough arguments for format string
```

Seems not straight forward to treat translations as untrusted.

2024-04-12 13:00 UTC, erig0 commented on po/sl.po
I will accept the changes to `wrong_args_for_callable()`. Sure.

I insist that this is fixed in the code and not in the translation. Fixing the code will implicitly also fix the translation.

We can use the positional based strings and then use `str.format()`. We should not use english keywords in format strings. Use positional arguments.

2024-04-12 14:56 UTC, erig0 commented on po/sl.po
```patch
diff --git a/src/firewall-applet.in b/src/firewall-applet.in
index 0d4a3067e0ab..6c35b488748e 100755
--- a/src/firewall-applet.in
+++ b/src/firewall-applet.in
@@ -720,7 +720,7 @@ class TrayApplet(QtWidgets.QSystemTrayIcon):
             zone = nm_get_zone_of_connection(connection)
             connections[connection] = [zone, connection_name]
 
-        binding = _("{entry} (Zone: {zone})")
+        binding = _("{} (Zone: {})")
 
         # add NM controlled bindings
         for connection in sorted(connections):
@@ -738,7 +738,7 @@ class TrayApplet(QtWidgets.QSystemTrayIcon):
                 )
             else:
                 action = QAction(
-                    escape(binding.format(zone=zone, entry=connection_name)), self
+                    escape(binding.format(zone, connection_name)), self
                 )
             action.triggered.connect(
                 functools.partial(
@@ -753,7 +753,7 @@ class TrayApplet(QtWidgets.QSystemTrayIcon):
         # add other interfaces
         for interface in sorted(interfaces):
             zone = interfaces[interface]
-            action = QAction(escape(binding.format(zone=zone, entry=interface)), self)
+            action = QAction(escape(binding.format(zone, interface)), self)
             action.triggered.connect(
                 functools.partial(self.zone_interface_editor, interface, zone)
             )
@@ -764,7 +764,7 @@ class TrayApplet(QtWidgets.QSystemTrayIcon):
 
         for source in sorted(sources):
             zone = sources[source]
-            action = QAction(escape(binding.format(zone=zone, entry=source)), self)
+            action = QAction(escape(binding.format(zone, source)), self)
             action.triggered.connect(
                 functools.partial(self.zone_source_editor, source, zone)
             )
```

2024-04-12 15:13 UTC, thom311 commented on po/sl.po
As said, I don't think this solves any problem. Which problem does it solve?

2024-04-12 15:20 UTC, thom311 commented on po/sl.po
> As said, I don't think this solves any problem. Which problem does it solve?

I am saying this, because you can still generate bogus (or even harmful/maliscious) translations that result in an exception (or worse). What problem does it avoid?

2024-04-12 18:51 UTC, erig0 commented on po/sl.po
> As said, I don't think this solves any problem. Which problem does it solve?

1. The current buggy translation will disappear when language translations are regenerated. You could update the pot file in this PR as well.
2. We avoid having english variable names in the doctext string. So they don't get mistakenly translated again in the future.

It's true that a bad translation could cause issues. I still thing this is less error prone.

```python
>>> "{0} foobar {1}".format("one")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: Replacement index 1 out of range for positional args tuple
>>> "{0} foobar".format("one", "two")
'one foobar'
```


Look, you can either change it as I've suggested. Or I'll take it over and make the change myself. I'm done bike shedding this topic.

2024-04-12 19:23 UTC, erig0 commented on po/sl.po
This is a mess. Using positional may avoid translators translating the variable name as was done here. Unfortunately it's still broken if someone removes a `{}`.

This is no real fix. Using `%` would avoid the security issue at least. That could be done in a different PR.

I will merge this as-is.

2024-04-12 19:24 UTC, erig0 approved these changes

2024-04-12 19:24 UTC, merged