add Kodi JSON-RPC and EventServer
firewalld/firewalld pull request #552
Opened 2019-12-05 11:08 UTC by nl6720

https://kodi.wiki/view/JSON-RPC_API#TCP
https://kodi.wiki/view/EventServer#Event_Clients_and_the_EventServer

2022-06-02 15:23 UTC, TorontoMedia requested changes
Thank you for submitting this pull request. Could you please address my change requests and if possible, add the type semantic to the commit message `feat(service): add Kodi JSON-RPC and EventServer services`

2022-06-02 15:23 UTC, TorontoMedia commented on config/services/kodi-JSON-RPC-TCP.xml
> +  <short>Kodi JSON-RPC (TCP)</short>
```suggestion
  <short>Kodi JSON-RPC</short>
```

2022-06-02 15:23 UTC, TorontoMedia commented on config/services/kodi-JSON-RPC-TCP.xml
> +  <description>A JSON-RPC interface using TCP transport to comunicate with Kodi.</description>
```suggestion
  <description>A JSON-RPC interface using TCP transport to communicate with Kodi.</description>
```

2022-06-02 15:23 UTC, TorontoMedia commented on po/POTFILES.in
> +config/services/kodi-JSON-RPC-TCP.xml
```suggestion
config/services/kodi-eventserver.xml
config/services/kodi-rpc.xml
```
Rename files as suggested.

2022-06-17 19:41 UTC, erig0 approved these changes
lgtm. Thanks @nl6720 and @TorontoMedia !

2022-06-17 19:42 UTC, merged

2022-07-24 06:04 UTC, marillat commented
Would be nice to know why these files have been added when kodi **already**
 provides these files since kodi 18 released in January 2019 ?
Also kodi install more services thans firewalld
https://github.com/xbmc/xbmc/tree/master/tools/Linux/firewalld-services

Wouldn't it be easier to let applications install firewalld services like systemd does?

2022-07-26 06:33 UTC, marillat commented
Thanks

2022-07-27 13:31 UTC, erig0 commented
> Would be nice to know why these files have been added when kodi **already** provides these files since kodi 18 released in January 2019 ? Also kodi install more services thans firewalld https://github.com/xbmc/xbmc/tree/master/tools/Linux/firewalld-services
> 
> Wouldn't it be easier to let applications install firewalld services like systemd does?

I was unaware Kodi provided its own service definitions.

I have no preference for if they're provided by the package or firewalld. If Kodi prefers to ship them, then great!

I will merge the the revert of this, #1002.