services: ssdp includes
firewalld/firewalld pull request #830
Opened 2021-07-28 11:02 UTC by marcosfrm

About...
https://github.com/firewalld/firewalld/blob/c11510e065fdbaeb8ff20f32e2628bdd70d30dd7/config/services/upnp-client.xml

can a service only include other?

2021-07-28 12:55 UTC, erig0 requested changes
> can a service only include other?

I'm not sure what you're asking. Services may include other services.

2021-07-28 12:55 UTC, erig0 commented on config/services/ssdp.xml
> +  <destination ipv4="239.255.255.250" ipv6="ff02::c"/>
Was this change intentional? Seems unrelated. Please remove.

2021-07-28 15:08 UTC, marcosfrm commented
> > can a service only include other?
> 
> I'm not sure what you're asking. Services may include other services.

I mean "UPnP Client" from a firewall POV is "UPnP discovery protocol", i.e. SSDP... hence can `upnp-client.xml` _only_ include ssdp?

2021-07-28 19:18 UTC, marcosfrm commented
https://github.com/firewalld/firewalld/blob/c11510e065fdbaeb8ff20f32e2628bdd70d30dd7/config/services/upnp-client.xml#L5

btw this is wrong, because the source port may be random for inbound traffic (M-SEARCH, NOTIFY).

2021-07-29 19:58 UTC, erig0 commented
> > > can a service only include other?
> > 
> > 
> > I'm not sure what you're asking. Services may include other services.
> 
> I mean "UPnP Client" from a firewall POV is "UPnP discovery protocol", i.e. SSDP... hence can `upnp-client.xml` _only_ include ssdp?

Sure. That effectively makes it an alias.

2021-07-29 20:00 UTC, erig0 commented
> https://github.com/firewalld/firewalld/blob/c11510e065fdbaeb8ff20f32e2628bdd70d30dd7/config/services/upnp-client.xml#L5
> 
> btw this is wrong, because the source port may be random for inbound traffic (M-SEARCH, NOTIFY).

Correct. It was wrong. `upnp-client` probably never worked. Having it include `ssdp` seems like the correct thing to do.

2021-07-30 13:13 UTC, erig0 approved these changes
Thanks!

2021-07-30 13:14 UTC, merged